# Generated by Django 2.0.9 on 2019-02-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_userimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infy',
            name='img',
        ),
        migrations.AlterField(
            model_name='userimage',
            name='img',
            field=models.ImageField(default='no-photo.png', upload_to=''),
        ),
    ]
