# Generated by Django 2.0.9 on 2019-02-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20190204_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='img',
            field=models.ImageField(default='no-photo.png', upload_to='user-img'),
        ),
    ]
